# Generated by Django 3.1.6 on 2021-02-10 17:41

from django.db import migrations, models
import quiz_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('instructions', models.TextField(default='Instructions here')),
                ('password', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(default=quiz_app.models.Quiz.default_start_datetime, verbose_name='start time')),
                ('end_date', models.DateTimeField(default=quiz_app.models.Quiz.default_end_datetime, verbose_name='end time')),
                ('duration', models.IntegerField(default=90)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
