# Generated by Django 3.1.6 on 2021-02-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20210211_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_bank',
            options={'ordering': ['tag', 'level']},
        ),
    ]
