# Generated by Django 3.1.6 on 2021-02-12 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20210211_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField(blank=True, null=True)),
                ('choice_4', models.TextField(blank=True, null=True)),
                ('choice_5', models.TextField(blank=True, null=True)),
                ('correct', models.TextField()),
                ('marks', models.IntegerField(default=1)),
                ('isShuffle', models.BooleanField(default=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz')),
            ],
            options={
                'verbose_name_plural': 'questions',
                'db_table': 'question',
                'ordering': ['marks'],
            },
        ),
        migrations.CreateModel(
            name='QuizTakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QuizTakers',
                'db_table': 'QuizTaker',
                'ordering': ['quiz', 'user'],
            },
        ),
        migrations.AlterModelOptions(
            name='question_bank',
            options={'ordering': ['tag', 'level'], 'verbose_name_plural': 'question_bank'},
        ),
        migrations.AddField(
            model_name='question_bank',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question_bank',
            name='level',
            field=models.CharField(choices=[('easy', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='easy', max_length=15),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('isCorrect', models.BooleanField(default=False)),
                ('marks', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
                ('quiztaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiztakers')),
            ],
            options={
                'verbose_name_plural': 'responses',
                'db_table': 'response',
                'ordering': ['quiztaker', 'question'],
            },
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('quiztaker', 'question'), name='Unique Response'),
        ),
    ]
