# Generated by Django 3.1.6 on 2021-02-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20210213_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
