# Generated by Django 3.1.6 on 2021-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20210214_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='isShuffle',
            field=models.BooleanField(default=True),
        ),
    ]
