# Generated by Django 3.1.6 on 2021-02-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_auto_20210216_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_backtracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='isProctered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_suspicion_count',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='quiztakers',
            name='suspicion_count',
            field=models.IntegerField(default=0),
        ),
    ]
