# Generated by Django 3.1.6 on 2021-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_auto_20210216_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztakers',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
