# Generated by Django 3.1.6 on 2021-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_auto_20210217_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='password',
            new_name='key',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='Description here'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='showResults',
            field=models.BooleanField(default=True),
        ),
    ]
