# Generated by Django 3.1.6 on 2021-02-19 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_auto_20210219_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='key',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
