# Generated by Django 3.1.6 on 2021-02-19 17:34

import django.core.validators
from django.db import migrations, models
import quiz_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_auto_20210219_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='key',
            field=models.CharField(default=quiz_app.models.Quiz.random_code, max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
