# Generated by Django 3.1.6 on 2021-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_auto_20210219_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='extra',
            field=models.TextField(default='Roll No'),
        ),
        migrations.AddField(
            model_name='quiztakers',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
