# Generated by Django 3.1.6 on 2021-02-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_auto_20210220_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='timeZone',
            field=models.CharField(default='UTC', max_length=30),
        ),
    ]
