# Generated by Django 3.1.6 on 2021-02-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0018_auto_20210224_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='isProctered',
            new_name='isProctored',
        ),
    ]
